
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bulir1
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile.nestjs
    container_name: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 
      DATABASE_NAME: bulir1

volumes:
  mysql-data:
    driver: local